[package]
name = "abpoa-rs"
version = "0.1.0"
edition = "2021"

include = [
    "abPOA/include",
    "abPOA/src",
    "abPOA/Makefile",
]
links = "abpoa"

[dependencies]

[build-dependencies]
bindgen = "0.70.1"
